### PR TITLE
Relegate hotdog to wackybox theme

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by choptop84** [comment]
Idk how to do this review stuff but no

**Comment by bsoap-cat** [comment]
Maybe try adding "Enable hotdog in description" in preferences?

**Comment by bsoap-cat** [comment]
and since the beepbox community loves it so much, it should remain enabled by default.

**Comment by MainCharacteroftheProblem** [comment]
> Maybe try adding "Enable hotdog in description" in preferences?

Well, there's already a "Hide Description" preference so it seems a bit redundant

**Review by Mid-The-Modder — APPROVED** [review]
Can't really see why everyone dislikes this. The hotdog did come from Wackybox and thus should remain an artifact in its theme, even if it's a funny joke in the community. If this weren't the case, why not rename panning to gentleman globally in Ultrabox and see how that goes? Yeah no that won't work.

**Comment by Mid-The-Modder** [comment]
(To be honest I just don't like joke aspects in mods lmfao)

**Comment by choptop84** [comment]
This is genuinely such a non-issue, most people don't even look at the description of ultrabox so removing the hotdog wouldn't have any effect other than a negative one since people like the hotdog. Overall my thoughts are: removing the hotdog is pointless and a waste of effort that could be spent elsewhere.

**Review by choptop84 — COMMENTED** [review]
I do not believe this is required or helpful.

**Review by choptop84 — CHANGES_REQUESTED** [review]
I will approve if this is added as a preference that was enabled by default. That way people who don't want the hotdog (nobody) doesn't have to see it.

**Comment by choptop84** [comment]
You added an Appearance tag to preferences, this would be a perfect preference for that tag specifically.

**Comment by MainCharacteroftheProblem** [comment]
> I will approve if this is added as a preference that was enabled by default. That way people who don't want the hotdog (nobody) doesn't have to see it.

As I said, I already added a "Show Description" preference so it seems a bit redundant

**Comment by choptop84** [comment]
Show Description and Show Hotdog are completely different,

**Comment by choptop84** [comment]
I just realized that if you really wanted the hotdog gone, you could just make a custom theme based off of the one you wanna use then just remove the hotdog in the custom theme. It's not like you can't do it, it's more people don't wanna go through the trouble of doing that.

**Comment by bsoap-cat** [comment]
> I just realized that if you really wanted the hotdog gone, you could just make a custom theme based off of the one you wanna use then just remove the hotdog in the custom theme. It's not like you can't do it, it's more people don't wanna go through the trouble of doing that.

Code for the hotdog removal?

**Comment by Mid-The-Modder** [comment]
Add this somewhere:
```
root:{
// Theme colors and what not
}
#Hotdog {
display: none;
}
```

**Comment by MainCharacteroftheProblem** [comment]
I need to update this eventually

**Comment by MainCharacteroftheProblem** [comment]
added in 2.2.10

**Pull request closed without merging**
