### PR TITLE
Port AB player

### LINKED ISSUE #153: Add Abyssbox Theatre Layout?

### PR DESCRIPTION
**Pull request by ghost**
More or less 1-1 port of Abyssbox's song player. The current issues that need to be fixed are:

- The song player doesn't immediately resize itself upon load (this is an issue in AB)
- The prompt code is kinda hacked in, so it doesn't account for the Frosted Glass preference (this is an issue in AB)
- The X on the song layout prompt doesn't show up (this is probably a mistake I made during porting)

Fixes #153

### CODE REVIEW

**Comment by MainCharacteroftheProblem** [comment]
@choptop84

**Comment by choptop84** [comment]
Hola

**Comment by choptop84** [comment]
So like, should I accept this review idk why I was pinged

**Comment by Mid-The-Modder** [comment]
Prob to review the code and see what's wrong with it (issues addressed)

**Comment by bsoap-cat** [comment]
does this mean you're able to see those buttons on the upper left corner of the editor?

**Comment by MainCharacteroftheProblem** [comment]
> does this mean you're able to see those buttons on the upper left corner of the editor?

No, the mobile buttons are not part of this pull request

**Pull request closed without merging**
