### PR TITLE
AbyssBox's focus layout

### PR DESCRIPTION
**Pull request by choptop84**

### CODE REVIEW

**Review by Mid-The-Modder — APPROVED** [review]
Those layouts will need to be ported regardless so this is a go from me.

**Review by MainCharacteroftheProblem — CHANGES_REQUESTED** [review]
please rename "focus" to "focused long" internally and externally

**Comment by MainCharacteroftheProblem** [comment]
(testing the requested changes thing)

**Comment by choptop84** [comment]
I changed the name to Focused Long

**Review by MainCharacteroftheProblem — APPROVED** [review]

**Pull request merged**
